# Use a imagem base do Python
FROM python:3.9

# Copie os arquivos necessários para dentro do contêiner
COPY . /app

# Defina o diretório de trabalho
WORKDIR /app

# Instale as dependências do Python
RUN pip install --no-cache-dir -r requirements.txt

# Comando de execução
CMD ["sh", "run.sh"]
